[package]
name = "terminoids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.44"
rand = "0.8.5"
termion = "2.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
